name: desafio_raro_labs
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter

  flutter:
    sdk: flutter

  # Widgets
  animated_splash_screen: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  super_rich_text:
    git: 'https://github.com/Bestfastfire/super_rich_text'
  oktoast: ^3.1.5

  # Flow
  flutter_svg_provider: ^0.1.10
  fragment_navigate: ^1.2.0+2
  google_fonts: ^2.1.0
  date_format: ^2.0.4
  intl: ^0.17.0
  get: ^4.6.1

  # Validate / Formatter
  mask_text_input_formatter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true